{% set name = "cfs3" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cfs3-{{ version }}.tar.gz
  sha256: 91e86d26c164f8f5e7997fd11fc026522a688384c21d611cf678a055a79b4274
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip !=21.3
    - setuptools >=80
    - setuptools_scm >=8
  run:
    - python {{ python_min }}
    - bitmath
    - cf-python
    - cmd2 >2
    - fsspec
    - minio
    - pyfive
    - udunits2

test:
  source_files:
    - tests
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pytest-html
    - pytest-metadata
    - pytest-mock
    - pytest-xdist
  commands:
    - pip check
    - pip install docker
    - pytest --ignore=tests/test_p5dump.py --ignore=tests/test_minio_stuff.py
    - s3view --help
  imports:
    - cfs3

about:
  home: https://github.com/NCAS-CMS/cfs3
  license: MIT
  license_file: LICENSE.txt
  summary: 'Lightweight tool for investigating data files in an s3 repository'

extra:
  recipe-maintainers:
    - valeriupredoi
